### PR TITLE
Update sitemap.xml

### PR DESCRIPTION
**Pull request by ArcEye**
New sitemap following changes to man1-3-9 component file names

In addition to individual google crawl submissions, should hopefully regenerate search results

### CODE REVIEW

**Comment by mhaberler** [comment]
you cannot do this in this rep

**Comment by ArcEye** [comment]
Enlighten me please, it is the only place it exists, I cannot remember how I put it there last time.

**Comment by mhaberler** [comment]
ioh, then it must have got lost or not added to the update
this is jushed to from the jenkins job, so it should live either in machinekit-docs or if generated by jekyll, it should travel with the push
at least I think its jekyll-generated
back late evenings

**Comment by ArcEye** [comment]
The one in this repo isn't the same one used on the site.

This one has not got any file extensions in it and was rejected by the google site AFAIR

I generated the one on the site and put it up there somehow, just got to remember how:)

**Comment by ArcEye** [comment]
Mystery solved, it **is** generated within jeykll or jenkins.
Not part of the process I was involved in.

The sitemap.xml is actually now up to date, but needed to be resubmitted.
That has been done and hopefully will speed up the search update.

**Pull request closed without merging**
